# Generated by Django 4.0 on 2022-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adg', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
