# Generated by Django 4.0.1 on 2022-04-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adg', '0004_blog_link_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default user.jpg', null=True, upload_to='blogs/'),
        ),
    ]
