# Generated by Django 4.0.1 on 2022-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adg', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='one_liner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
